import org.apache.commons.lang3.StringUtils;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

	public static void main(String args[]) {
		System.out.println("testtest!!!!!");
		System.out.println(StringUtils.left("abcdef", 5));
	}
}
